### ISSUE TITLE
Can't build project on 3.9.16

### ISSUE THREAD

**Issue by DearTanakorn** [TheSGJ/nextjs-toploader#138]
Can't build a project after update nextjs-toploader to 3.9.16 (revert to 3.8.16 is working)

Environment :
- Node : 20.18.3
- NextJS : 15.5.2

`
> next build

   ▲ Next.js 15.5.2
   - Environments: .env

   Linting and checking validity of types  .
 ⚠ The Next.js plugin was not detected in your ESLint configuration. See https://nextjs.org/docs/app/api-reference/config/eslint#migrating-existing-config
 ✓ Linting and checking validity of types    
   Creating an optimized production build ...
<w> [webpack.cache.PackFileCacheStrategy] Serializing big strings (128kiB) impacts deserialization performance (consider using Buffer instead and decode when needed)
 ✓ Compiled successfully in 18.7s
unhandledRejection [TypeError: o.oneOfType is not a function] { type: 'TypeError' }
`

**Comment by TheSGJ** [comment]
Can you provide the reproduction of this error using codesandbox or vercel?

Without reproduction of error it would be difficult to assume what's causing this error.

#### I have few questions:
Are you using turbopack?
Are you using turborepo or monorepo?
Can you share your eslint config (if possible)?

#### Few suggestions, that should fix this:
Try deleting the lock file of your package manager, see if this fixes the error.

#### From my end:
Tested the nextjs-toploader v3.9.16 on creating a new project on nextjs version 15.5.2 (`next build` working properly on my end)
using node version: v22

Deployed project on vercel (successfully deployed and nextjs-toploader is working properly)

Please let me know, if you know more about this if trying above suggestions and problem is still not fixed.

**Comment by saegeullee** [comment]
same error o.oneOfType is not a function. I'm moving to use nprogress instead.

**Comment by DearTanakorn** [comment]
> This error seems to be happening due to some conflict in monorepo (since you're using monorepo), but this version of package works fine in normal project.

sorry for a bit confused, this project just a normal project not related to any monorepo or turborepo.

**Comment by Daniel3711997** [comment]
same error here

**Comment by TheSGJ** [comment]
Please let me know by trying nextjs-toploader version 3.9.17 that if it works now on this version or not.

**Comment by DearTanakorn** [comment]
> Please let me know by trying nextjs-toploader version 3.9.17 that if it works now on this version or not.

work normally
